# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 859)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_example = QtWidgets.QWidget()
        self.tab_example.setObjectName("tab_example")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1081, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditImage = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditImage.setObjectName("lineEditImage")
        self.horizontalLayout.addWidget(self.lineEditImage)
        self.pbImageOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbImageOpen.setObjectName("pbImageOpen")
        self.horizontalLayout.addWidget(self.pbImageOpen)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 60, 861, 691))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mpl = MplWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.horizontalLayout_2.addWidget(self.mpl)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 211, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.sbCrop = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.sbCrop.setMaximumSize(QtCore.QSize(85, 16777215))
        self.sbCrop.setMaximum(100)
        self.sbCrop.setSingleStep(10)
        self.sbCrop.setProperty("value", 50)
        self.sbCrop.setObjectName("sbCrop")
        self.horizontalLayout_3.addWidget(self.sbCrop)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 211, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sbBlob = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.sbBlob.setMaximumSize(QtCore.QSize(85, 16777215))
        self.sbBlob.setMaximum(150)
        self.sbBlob.setSingleStep(10)
        self.sbBlob.setObjectName("sbBlob")
        self.horizontalLayout_4.addWidget(self.sbBlob)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 260, 211, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbDead = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.cbDead.setObjectName("cbDead")
        self.horizontalLayout_5.addWidget(self.cbDead)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(30, 300, 192, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbExport = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pbExport.setObjectName("pbExport")
        self.horizontalLayout_6.addWidget(self.pbExport)
        self.pbUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pbUpdate.setObjectName("pbUpdate")
        self.horizontalLayout_6.addWidget(self.pbUpdate)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_example)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 120, 212, 80))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.cbYellow = QtWidgets.QCheckBox(self.horizontalLayoutWidget_9)
        self.cbYellow.setObjectName("cbYellow")
        self.horizontalLayout_9.addWidget(self.cbYellow)
        self.tabWidget.addTab(self.tab_example, "")
        self.tab_directory = QtWidgets.QWidget()
        self.tab_directory.setObjectName("tab_directory")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_directory)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 120, 851, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEditDirIn = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditDirIn.setObjectName("lineEditDirIn")
        self.horizontalLayout_7.addWidget(self.lineEditDirIn)
        self.pbDirectoryOpen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbDirectoryOpen.setObjectName("pbDirectoryOpen")
        self.horizontalLayout_7.addWidget(self.pbDirectoryOpen)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.sbCropDir = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sbCropDir.setMaximumSize(QtCore.QSize(85, 16777215))
        self.sbCropDir.setMaximum(100)
        self.sbCropDir.setSingleStep(10)
        self.sbCropDir.setProperty("value", 50)
        self.sbCropDir.setObjectName("sbCropDir")
        self.horizontalLayout_11.addWidget(self.sbCropDir)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(28, 16777215))
        self.label_6.setText("")
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.cbYellowDir = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cbYellowDir.setObjectName("cbYellowDir")
        self.horizontalLayout_10.addWidget(self.cbYellowDir)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(143, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.sbBlobDir = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sbBlobDir.setMinimumSize(QtCore.QSize(85, 0))
        self.sbBlobDir.setMaximumSize(QtCore.QSize(85, 16777215))
        self.sbBlobDir.setMaximum(150)
        self.sbBlobDir.setSingleStep(10)
        self.sbBlobDir.setObjectName("sbBlobDir")
        self.horizontalLayout_12.addWidget(self.sbBlobDir)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.cbDeadDir = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cbDeadDir.setObjectName("cbDeadDir")
        self.horizontalLayout_13.addWidget(self.cbDeadDir)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEditDirOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditDirOut.setObjectName("lineEditDirOut")
        self.horizontalLayout_8.addWidget(self.lineEditDirOut)
        self.pbDirectoryExport = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbDirectoryExport.setObjectName("pbDirectoryExport")
        self.horizontalLayout_8.addWidget(self.pbDirectoryExport)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.label_6.raise_()
        self.gridLayoutWidget.raise_()
        self.tabWidget.addTab(self.tab_directory, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSingle_Image = QtWidgets.QAction(MainWindow)
        self.actionSingle_Image.setObjectName("actionSingle_Image")
        self.menuOpen.addAction(self.actionSingle_Image)
        self.menuOpen.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditImage.setPlaceholderText(_translate("MainWindow", "/home/rio/Dokumente/Uni/Bachelorarbeit/arnika/Project/output/IMAGE"))
        self.pbImageOpen.setText(_translate("MainWindow", "Open"))
        self.label.setText(_translate("MainWindow", "Image Size in %"))
        self.label_2.setText(_translate("MainWindow", "Min Flower Size"))
        self.cbDead.setText(_translate("MainWindow", "show dead flowers"))
        self.pbExport.setText(_translate("MainWindow", "Export"))
        self.pbUpdate.setText(_translate("MainWindow", "Update"))
        self.label_3.setText(_translate("MainWindow", "segmentation"))
        self.cbYellow.setText(_translate("MainWindow", "yellow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_example), _translate("MainWindow", "Example"))
        self.label_4.setText(_translate("MainWindow", "Import all Images from Directory:"))
        self.lineEditDirIn.setPlaceholderText(_translate("MainWindow", "/home/rio/Dokumente/Uni/Bachelorarbeit/arnika/Project/"))
        self.pbDirectoryOpen.setText(_translate("MainWindow", "Import"))
        self.label_7.setText(_translate("MainWindow", "Crop image to %"))
        self.cbYellowDir.setText(_translate("MainWindow", "yellow segmentation"))
        self.label_8.setText(_translate("MainWindow", "Min Flower Size"))
        self.cbDeadDir.setText(_translate("MainWindow", "remove dead flowers"))
        self.label_5.setText(_translate("MainWindow", "Export to Directory:"))
        self.lineEditDirOut.setPlaceholderText(_translate("MainWindow", "/home/rio/Dokumente/Uni/Bachelorarbeit/arnika/Project/Output/"))
        self.pbDirectoryExport.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_directory), _translate("MainWindow", "Directory"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionOpen.setText(_translate("MainWindow", "from Directory"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSingle_Image.setText(_translate("MainWindow", "single Image"))

from package.gui.mplwidget import MplWidget

